### ISSUE TITLE
jetty jars /version

### ISSUE THREAD

**Issue by ghost** [TimelyPick/HtmlSpeed#3]
Hi, I tried to run. 

What version of jetty jars do I need?
What jars?

Cheers

**Comment by eldad314** [comment]
Hi

I have added the section "Starting HtmlSpeed" to the README file.
You will find the answer there.

In a few days from now I will add a complete ready-to-run example.

In the meantime you can package all Java source files in a war-file and
create the directory "htmlspeed" under Jetty home-directory, In that
directory you should place the properties.txt file and all other configuration files.

**Comment by ghost** [comment]
I got it, it's a war w/ a servlet, not jar. Any reason it would not work w/ Jetty 9?

**Comment by eldad314** [comment]
Now you can download a ready-to-run example.
Read the "Example" section in the README file.
